version: 2.1

orbs:
  node: circleci/node@3.0.0

references:
  PLUGIN_PATH: &PLUGIN_PATH
    ~/project/wordpress-develop/src/wp-content/plugins/genesis-custom-blocks

executors:
  php:
    docker:
      - image: circleci/php:7.4.5-cli-node

commands:
  set-up-packages:
    description: "Installing packages and building"
    steps:
      - run: composer install && npm install && npm run build

  install-composer:
    description: "Installing Composer"
    steps:
      - run:
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            EXPECTED_SIGNATURE=$(curl -s https://composer.github.io/installer.sig)
            ACTUAL_SIGNATURE=$(php -r "echo hash_file('sha384', 'composer-setup.php');")
            [[ "$EXPECTED_SIGNATURE" == "$ACTUAL_SIGNATURE" ]] && sudo php composer-setup.php --install-dir=/bin --filename=composer || exit 1

jobs:
  lint:
    executor:
      name: php
    steps:
      - checkout
      - set-up-packages
      - run: npm run lint

  php-tests:
    parameters:
      php-version:
        type: string
    docker:
      - image: circleci/php:<< parameters.php-version >>-cli-node
        environment:
          WP_TESTS_DIR: ~/project/wordpress-develop/tests/phpunit
      - image: mysql:5.7
        environment:
          MYSQL_DATABASE: youremptytestdbnamehere
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: yourusernamehere
          MYSQL_PASSWORD: yourpasswordhere
          MYSQL_ROOT_PASSWORD: wordpress
    steps:
      - run:
          name: Installing the mysqli extension
          command: sudo docker-php-ext-install mysqli
      - install-composer
      - node/install:
          node-version: lts
      - run:
          name: Installing WordPress and setting up tests
          command: |
            git clone git://develop.git.wordpress.org/ wordpress-develop
            cp wordpress-develop/wp-tests-config-sample.php wordpress-develop/wp-tests-config.php
            sed -i 's/localhost/127.0.0.1/g' wordpress-develop/wp-tests-config.php
      - run: mkdir -p *PLUGIN_PATH
      - checkout:
          path: *PLUGIN_PATH
      - run:
          name: Running PHPUnit
          working_directory: *PLUGIN_PATH
          command: |
            composer install && npm install && npm run build
            composer require --dev phpunit/phpunit 5.7.9
            WP_TESTS_DIR=~/project/wordpress-develop/tests/phpunit ./vendor/bin/phpunit

  js-tests:
    executor: php
    steps:
      - checkout
      - run: npm ci && npm run test:js

  e2e-tests:
    machine:
      image: ubuntu-1604:202004-01
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install php php-xml
      - install-composer
      - node/install:
          node-version: lts
      - set-up-packages
      - run: npm run env start && npm run test:e2e

workflows:
  lint-all:
    jobs:
      - lint
  tests:
    jobs:
      - php-tests:
          matrix:
            parameters:
              php-version: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4' ]
      - js-tests
      - e2e-tests
